[versions]
kotlinx-serialization-version = "1.6.2"
kotlinx-io-version = "0.3.0"
kotlinx-datetime-version = "0.5.0"
kotlinx-coroutines-bom = "1.7.3"

[libraries]
kotlinx-serialization-bom = { module = "org.jetbrains.kotlinx:kotlinx-serialization-bom", version.ref = "kotlinx-serialization-version" }
kotlinx-coroutines-bom = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version.ref = "kotlinx-coroutines-bom" }
kotlinx-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io-version" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime-version" }

[bundles]

[plugins]
