[versions]
gradle = "8.6"
jvm = "17"
kotlin = "1.9.22"
kotlin-jvm-target = "17"
kotlin-dsl-jvm-target = "17"
kotlin-api-version = "1.6"
kotlin-language-version = "2.0"
detekt = "1.23.4"
dokka = "1.9.10"
kover = "0.7.5"
binary-compatibility-validator = "0.13.2"

[libraries]
jetBrains-dokka-base = { module = "org.jetbrains.dokka:dokka-base", version.ref = "dokka" }
jetBrains-dokka-gradle = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }

[bundles]

[plugins]
org-jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
org-jetbrains-kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
org-jetbrains-kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
org-jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
org-jetbrains-kotlinx-binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binary-compatibility-validator" }
io-gitlab-arturbosch-detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
